name = "SimpleArgParse"
uuid = "4c739d64-e22d-44e1-ada1-53a1c3c0e953"
authors = ["Adam Erickson <adam.michael.erickson@gmail.com>"]
version = "1.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.0"
OrderedCollections = "1.5"
